// <auto-generated />
using BackendGerenciamentoEquipeEmpresarial.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendGerenciamentoEquipeEmpresarial.Infrastructure.Migrations
{
    [DbContext(typeof(BackendGerenciamentoEquipeEmpresarialContext))]
    partial class BackendGerenciamentoEquipeEmpresarialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendGerenciamentoEquipeEmpresarial.Domain.Entities.GroupPermission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TaskPermissionDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskPermissionEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("TaskPermissionInsert")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GroupPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Name = "Admin",
                            TaskPermissionDelete = true,
                            TaskPermissionEdit = true,
                            TaskPermissionInsert = true
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            Name = "Membro",
                            TaskPermissionDelete = true,
                            TaskPermissionEdit = true,
                            TaskPermissionInsert = true
                        });
                });

            modelBuilder.Entity("BackendGerenciamentoEquipeEmpresarial.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupPermissionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupPermissionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendGerenciamentoEquipeEmpresarial.Domain.Entities.User", b =>
                {
                    b.HasOne("BackendGerenciamentoEquipeEmpresarial.Domain.Entities.GroupPermission", "GroupPermission")
                        .WithMany()
                        .HasForeignKey("GroupPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupPermission");
                });
#pragma warning restore 612, 618
        }
    }
}
