@BackendGerenciamentoEquipeEmpresarial.Presentation_HostAddress = http://localhost:5062

GET {{BackendGerenciamentoEquipeEmpresarial.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###
